dubbo:
  application:
    name: ims-server
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.lujiatao.ims.server.service.impl
server:
  port: 9001
spring:
  datasource:
    #使用MySQL数据库
    #    url: jdbc:mysql://yourip:yourport/ims
    #    username: yourusername
    #    password: yourpassword
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用H2数据库
    url: jdbc:h2:tcp://localhost/~/ims;IFEXISTS=true
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    #初始化建表语句
    schema: classpath:sql/schema.sql
    #初始化数据
    data: classpath:sql/data.sql
    initialization-mode: always
    sql-script-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true